apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: raffaelklingler-raffaelklingler-poi-gateway-app-dev
  annotations:
    argocd/app-name: raffaelklingler-raffaelklingler-poi-gateway-app-dev
    backstage.io/kubernetes-id: raffaelklingler-raffaelklingler-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: raffaelklingler
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=raffaelklingler-raffaelklingler-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/raffaelklingler-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/raffaelklingler/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/raffaelklingler/deployments/raffaelklingler-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/raffaelklingler-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/raffaelklingler"
  system: workshop-system-raffaelklingler
  providesApis:
    - gateway-api-raffaelklingler
  consumesApis:
    - backend-api-raffaelklingler
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-raffaelklingler
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/raffaelklingler"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-raffaelklingler
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://raffaelklingler-poi-gateway-app-raffaelklingler.apps.summit23blues.6mbu.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus2/raffaelklingler-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/raffaelklingler"
  system: workshop-system-raffaelklingler
  definition:
    $text: https://github.com/Summit23Janus2/raffaelklingler-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
